#!/bin/bash

USER_HOME=$(eval echo ~${SUDO_USER})
PATH_TO_SERVER_LOCATION="$USER_HOME/truenas"
PATH_TO_SCRIPTS="$USER_HOME/bash-nuc"

export PATH_TO_SERVER_LOCATION
export PATH_TO_SCRIPTS
export USER_HOME