version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "2080:80/tcp"
    environment:
      TZ: 'Europe/Zurich'
      WEBPASSWORD: '${USE_PIHOLE_PASSWD}'
      DNS1: 9.9.9.9
      DNS2: 8.8.8.8
    volumes:
      - '${HOME}/docker_data/pihole/etc-pihole:/etc/pihole'
      - '${HOME}/docker_data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'     
    restart: unless-stopped