version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
      - "2080:80/tcp" # Web Interface
    environment:
      TZ: 'Europe/Zurich'
      WEBPASSWORD: '${USE_PIHOLE_PASSWD}'
      DNS1: 9.9.9.9
      DNS2: 8.8.8.8
    volumes:
      - '${USED_DOCKER_DATA}/pihole/etc:/etc/pihole'
      - '${USED_DOCKER_DATA}/pihole/dnsmasq.d:/etc/dnsmasq.d'     
    restart: unless-stopped