version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    ports:
      - '80:80' # HTTP
      - '81:81' # HTTP Admin
      - '443:443' # HTTPS
    volumes:
      - ${USED_DOCKER_DATA}/nginx/data:/data
      - ${USED_DOCKER_DATA}/nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ${USED_DOCKER_DATA}/nginx/data/mysql:/var/lib/mysql