version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ${NOW_DOCKER_DATA}/uptime-kuma-data:/app/data
    ports:
      - 3001:3001 
    restart: always