version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - SERVERURL={$USE_IP}
      - SERVERPORT=51820
      - PEERS=4
      - PEERDNS=${USE_DNS}
      - dns_server_ip=${USE_DNS}
    ports:
      - 51820:51820/udp
    volumes:
      - /lib/modules:/lib/modules
      - ${NOW_DOCKER_DATA}/wireguard:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1