version: "2"
services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    restart: unless-stopped

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - SERVERPORT=51820
      - PEERS=4
      - PEERDNS=${dns_server_ip}
    ports:
      - 51820:51820/udp
    volumes:
      - /lib/modules:/lib/modules
      - ${HOME}/wireguard:/config